site_name: CEALing Scriptures
site_url: https://cealingscriptures.ceallearning.net
repo_url: https://github.com/bryanpc01/cealing-scriptures
repo_name: bryanpc01/cealing-scriptures
edit_uri: edit/main/docs/
theme:
  name: material
  font:
    text: Noto Sans
    code: JetBrains Mono
  language: en
  icon:
    logo: material/notebook-outline
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
      primary: deep orange
      accent: orange

    # Palette toggle for light theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep orange
      accent: orange

    # Palette toggle for dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: deep orange
      accent: orange
  features:
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
  - blog:
      blog_toc: true
      post_date_format: full
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 1
      post_readtime: true
      post_readtime_words_per_minute: 240
      archive: false
      authors_file: blog/.authors.yml
      categories_allowed:
        - Apocalyptic
        - Epistles
        - Gospels
        - Lament
        - Parables
        - Poetry
        - Wisdom
        - Law
        - Historical Narrative
        - Love
        - Faith
        - Grace
        - Redemption
        - Forgivness
        - Salvation
        - Covenant
        - Justice
        - Peace
        - Hope
        - Holiness
        - Obedience
        - Sin
        - Suffering
        - Judgement
        - Creation
        - Eschatology
        - Mission
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/phil-bryan
    - icon: fontawesome/brands/github
      link: https://github.com/bryanpc01
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/phil_nass/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/bryanceal
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zRNZ43Kh
copyright: >
  Copyright &copy; 2024 - CEAL Learning LLC â€“
  <a href="#__consent">Change cookie settings</a>

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- md_in_html